### PR TITLE
Fix TlsCredentialsOptions enablement issue

### PR DESCRIPTION
**Pull request by ravigumm**
Also fix tests script and enable test_flight tests
Signed-off-by: Ravi Gummadi <ravigumm@in.ibm.com>

## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/open-ce/open-ce/blob/main/CONTRIBUTING.md)?
- [ ] Did you update any affected [documentation](https://github.com/open-ce/open-ce/blob/main/doc/)?
- [x] Did you write any tests to validate this change?

## Description
Fix TlsCredentialsOptions enablement issue in arrow related to grpc.

Fixes # (issue).
https://github.com/open-ce/pyarrow-feedstock/issues/17

## Review process to land 

1. All tests and other checks must succeed.
2. At least one [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) must review and approve.
3. If any  [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) requests changes, they must be addressed.

### CODE REVIEW

**Comment by ravigumm** [comment]
This PR is for https://github.com/open-ce/pyarrow-feedstock/issues/17
______
The fix is from https://github.com/apache/arrow/pull/9569 . The test failure issue seen on s390x(test case test_tls_disable_server_verification) got resolved with this fix and was failing without the fix.
```
pyarrow.lib.ArrowNotImplementedError: Using encryption with server verification disabled is unsupported. Please use a release of Arrow Flight built with gRPC 1.27 or higher.
```
_____
From arrow build logs, TlsCredentialsOptions getting enabled:
```
-- Checking support for TlsCredentialsOptions (gRPC >= 1.36)...
-- Change Dir: /root/miniconda3/envs/opence5/conda-bld/arrow-cpp-ext_1627081202531/work/cpp/build/src/arrow/flight/try_compile/CMakeFiles/CMakeTmp

Run Build Command(s):/root/miniconda3/envs/opence5/conda-bld/arrow-cpp-ext_1627081202531/_build_env/bin/ninja cmTC_7f278 && [1/2] Building CXX object CMakeFiles/cmTC_7f278.dir/check_tls_opts_136.cc.o
[2/2] Linking CXX executable cmTC_7f278


-- Found approximate gRPC version: 1.36 (ARROW_FLIGHT_REQUIRE_TLSCREDENTIALSOPTIONS=ON)
```
_____
I had to fix couple of lines in tests/open-ce-tests.yaml so that
(1) ARROW_TEST_DATA gets cloned (arrow/testing git submodule was not getting cloned and thus testing/data directory was not there)
(2) Set ARROW_TEST_DATA to testing/data directory instead of testing directory. Without this directory change, pytests were throwing errors.
(3) Enabled test_flight in pytests
_____

test_flight set of tests now give 51 passed instead of the earlier 50 passed result. The specific test case test_tls_disable_server_verification has pytest.skip in exception catch block for NotImplementedError.

python -m pytest -k "test_flight" $PYARROW_LOCATION
```
=================================================== test session starts ====================================================
platform linux -- Python 3.8.10, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /root
plugins: hypothesis-6.8.5, lazy-fixture-0.6.3
collected 3692 items / 3634 deselected / 3 skipped / 55 selected                                                           

../../../miniconda3/envs/pyarrow76/lib/python3.8/site-packages/pyarrow/tests/test_flight.py ...s..s.........s....s.. [ 41%]
.........s.......ss...............                                                                                   [100%]

===================================================== warnings summary =====================================================
../../../miniconda3/envs/pyarrow76/lib/python3.8/site-packages/pyarrow/tests/test_serialization.py:283
  /root/miniconda3/envs/pyarrow76/lib/python3.8/site-packages/pyarrow/tests/test_serialization.py:283: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(scope='session')

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================ 51 passed, 10 skipped, 3634 deselected, 1 warning in 2.62s ================================
```

**Comment by ravigumm** [comment]
@jayfurmanek , Would you please review the PR ? Thanks.

**Comment by bnemanich** [comment]
Cool! This looks good to me. For the patch name, I think there is a specific format that we normally use. @jayfurmanek can probably give you the details. Thanks for fixing this an enabling the test!

**Comment by jayfurmanek** [comment]
yeah - let's name the patch `0301-fix-option-to-disable-TLS- verification`

**Comment by ravigumm** [comment]
Renamed the patch file name to 0301-fix-option-to-disable-TLS-verification.patch now.
@bnemanich , @jayfurmanek , Would you please review the other PR (not related to this fix) https://github.com/open-ce/open-ce/pull/462 also ? Thanks

**Review by bnemanich — APPROVED** [review]

**Review by jayfurmanek — APPROVED** [review]

**Comment by jayfurmanek** [comment]
It looks like the new cmake output becomes:

```
-- Checking support for TlsCredentialsOptions (gRPC >= 1.36)...
-- Change Dir: /root/anaconda3/conda-bld/arrow-cpp-ext_1627311775461/work/cpp/build/src/arrow/flight/try_compile/CMakeFiles/CMakeTmp

Run Build Command(s):/root/anaconda3/conda-bld/arrow-cpp-ext_1627311775461/_build_env/bin/ninja cmTC_94737 && [1/2] Building CXX object CMakeFiles/cmTC_94737.dir/check_tls_opts_136.cc.o
[2/2] Linking CXX executable cmTC_94737


-- Found approximate gRPC version: 1.36 (ARROW_FLIGHT_REQUIRE_TLSCREDENTIALSOPTIONS=ON)
```

**Comment by jayfurmanek** [comment]
Unit tests pass on bot `x86_64` and `ppc64le`.
This one can be merged.

**Comment by ravigumm** [comment]
Yes Jason. I pasted the same logs(cmake output) above from my build on s390x also.
Thanks

**Pull request merged**
